import type { Patient, Appointment, VitalReading, Encounter, Medication, Allergy, Diagnosis } from "@/types";

const margaretThompson: Patient = {
  id: "margaret-thompson",
  mrn: "RMH-284710",
  medicareNumber: "2847 10391 1",
  ihi: "8003 6288 0001 4725",
  firstName: "Margaret",
  lastName: "Thompson",
  dob: "1951-09-14",
  age: 74,
  sex: "Female",
  bloodType: "O+",
  address: "42 Brunswick Rd, Fitzroy VIC 3065",
  phone: "0412 847 391",
  nextOfKin: { name: "Patricia Thompson", relationship: "Daughter", phone: "0423 918 472" },
  gp: { name: "Dr Alan Brock", practice: "Fitzroy Medical Centre", phone: "(03) 9417 2830" },
  ward: "4B",
  bedNumber: "12",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-22",
  treatingClinician: "Dr James Chen",
  department: "Cardiology",
  fallsRisk: "Medium",
  ewsScore: 3,
  alerts: [],
  allergies: [
    { allergen: "Aspirin", type: "Drug", reaction: "Bronchospasm", severity: "Severe", verified: true },
    { allergen: "Penicillin", type: "Drug", reaction: "Urticarial rash", severity: "Moderate", verified: true },
  ],
  diagnoses: [
    { icdCode: "I21.0", description: "Anterior ST-elevation myocardial infarction", shortName: "Anterior STEMI", status: "Active" },
    { icdCode: "I10", description: "Essential hypertension", shortName: "Hypertension", status: "Chronic" },
    { icdCode: "E78.5", description: "Hyperlipidaemia", shortName: "Hyperlipidaemia", status: "Chronic" },
  ],
  medications: [
    { id: "m-mt-1", name: "Clopidogrel", brandName: "Plavix", dose: "75mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr James Chen", startDate: "2026-04-22" },
    { id: "m-mt-2", name: "Metoprolol", brandName: "Betaloc", dose: "50mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr James Chen", startDate: "2026-04-22" },
    { id: "m-mt-3", name: "Atorvastatin", brandName: "Lipitor", dose: "80mg", frequency: "Nocte", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr James Chen", startDate: "2026-04-22" },
    { id: "m-mt-4", name: "Enoxaparin", brandName: "Clexane", dose: "80mg", frequency: "BD", route: "SC", status: "Active", isHighAlert: true, prescriber: "Dr James Chen", startDate: "2026-04-22" },
    { id: "m-mt-5", name: "Ramipril", dose: "5mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr James Chen", startDate: "2026-04-22" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 148, diastolicBP: 94, heartRate: 82, respiratoryRate: 20, temperature: 37.3, oxygenSaturation: 94, ewsScore: 5, painScore: 7 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 145, diastolicBP: 92, heartRate: 80, respiratoryRate: 19, temperature: 37.2, oxygenSaturation: 95, ewsScore: 4, painScore: 6 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 142, diastolicBP: 90, heartRate: 78, respiratoryRate: 18, temperature: 37.1, oxygenSaturation: 95, ewsScore: 4, painScore: 5 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 140, diastolicBP: 88, heartRate: 78, respiratoryRate: 18, temperature: 37.0, oxygenSaturation: 96, ewsScore: 3, painScore: 4 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 138, diastolicBP: 88, heartRate: 76, respiratoryRate: 18, temperature: 37.1, oxygenSaturation: 96, ewsScore: 3, painScore: 4 },
  ],
  encounters: [
    {
      id: "enc-mt-1",
      type: "Admission",
      date: "2026-04-22",
      facility: "Royal Melbourne Hospital",
      department: "Cardiology",
      clinician: "Dr James Chen",
      note: {
        subjective: "74yo female presented via ambulance with acute chest pain onset 0340. Diaphoretic, SOB. Aspirin allergy documented — clopidogrel loading dose given instead. ECG: anterior ST elevation leads V1-V4.",
        objective: "HR 92 BP 162/98 SpO2 94% on 4L O2. Troponin I 8.4 (markedly elevated). ECG confirmed STEMI. CXR mild pulmonary oedema.",
        assessment: "Anterior STEMI. Aspirin allergy — clopidogrel-based antiplatelet therapy. Cardiogenic compromise.",
        plan: "Emergency PPCI performed — LAD stented. ICU post-procedure monitoring. Enoxaparin, Metoprolol, Atorvastatin commenced.",
      },
    },
    {
      id: "enc-mt-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Cardiology",
      clinician: "Dr James Chen",
      note: {
        subjective: "Patient reports chest discomfort 4/10, improved from admission. Mild dyspnoea on exertion. Denies palpitations.",
        objective: "HR 76 BP 138/88 SpO2 96% RA. Wound sites clean. Echo: EF 48% (reduced from estimated 60%). Troponin trending down.",
        assessment: "Post-PPCI day 2. Haemodynamically stable. Reduced EF requiring optimisation.",
        plan: "Continue dual antiplatelet. Uptitrate Ramipril. Cardiology review in 6 weeks. Cardiac rehab referral. Lifestyle counselling.",
      },
    },
  ],
};

const robertAdeyemi: Patient = {
  id: "robert-adeyemi",
  mrn: "RMH-619082",
  medicareNumber: "6190 82341 2",
  ihi: "8003 7421 0009 3812",
  firstName: "Robert",
  lastName: "Adeyemi",
  dob: "1963-03-22",
  age: 61,
  sex: "Male",
  bloodType: "A+",
  address: "18 Station St, Coburg VIC 3058",
  phone: "0438 291 047",
  nextOfKin: { name: "Grace Adeyemi", relationship: "Wife", phone: "0411 382 947" },
  gp: { name: "Dr Maria Santos", practice: "Coburg Family Practice", phone: "(03) 9354 1920" },
  ward: "4A",
  bedNumber: "7",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-21",
  treatingClinician: "Dr Patricia Lam",
  department: "Endocrinology",
  fallsRisk: "Low",
  ewsScore: 1,
  alerts: [],
  allergies: [
    { allergen: "Metformin", type: "Drug", reaction: "Severe GI intolerance, nausea and vomiting", severity: "Mild", verified: true },
  ],
  diagnoses: [
    { icdCode: "E11.9", description: "Type 2 diabetes mellitus without complications", shortName: "T2DM", status: "Chronic" },
    { icdCode: "I10", description: "Essential hypertension", shortName: "Hypertension", status: "Chronic" },
    { icdCode: "N18.3", description: "Chronic kidney disease stage 3", shortName: "CKD Stage 3", status: "Chronic" },
  ],
  medications: [
    { id: "m-ra-1", name: "Insulin Glargine", brandName: "Lantus", dose: "20 units", frequency: "Nocte", route: "SC", status: "Active", isHighAlert: true, prescriber: "Dr Patricia Lam", startDate: "2026-04-21" },
    { id: "m-ra-2", name: "Amlodipine", dose: "10mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Patricia Lam", startDate: "2026-04-21" },
    { id: "m-ra-3", name: "Perindopril", dose: "8mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Patricia Lam", startDate: "2026-04-21" },
    { id: "m-ra-4", name: "Metformin", dose: "1000mg", frequency: "BD", route: "Oral", status: "Ceased", isHighAlert: false, prescriber: "Dr Maria Santos", startDate: "2025-01-10" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 160, diastolicBP: 96, heartRate: 74, respiratoryRate: 16, temperature: 36.9, oxygenSaturation: 97, ewsScore: 2, painScore: 2, glucoseBSL: 17.4 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 156, diastolicBP: 94, heartRate: 73, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 98, ewsScore: 1, painScore: 2, glucoseBSL: 14.2 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 152, diastolicBP: 92, heartRate: 72, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 98, ewsScore: 1, painScore: 2, glucoseBSL: 11.8 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 150, diastolicBP: 92, heartRate: 72, respiratoryRate: 16, temperature: 36.7, oxygenSaturation: 98, ewsScore: 1, painScore: 2, glucoseBSL: 10.4 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 148, diastolicBP: 92, heartRate: 72, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 98, ewsScore: 1, painScore: 2, glucoseBSL: 9.2 },
  ],
  encounters: [
    {
      id: "enc-ra-1",
      type: "Admission",
      date: "2026-04-21",
      facility: "Royal Melbourne Hospital",
      department: "Endocrinology",
      clinician: "Dr Patricia Lam",
      note: {
        subjective: "61yo male admitted for BSL optimisation. HbA1c 9.8% at last check. Metformin ceased due to CKD (eGFR 42). Reports polyuria, polydipsia for past 2 weeks. BP poorly controlled at home.",
        objective: "BSL 17.4 on admission. BP 162/96. eGFR 42. UEC: Na 138 K 4.1 Cr 142. HbA1c 9.8%.",
        assessment: "Poorly controlled T2DM with CKD stage 3. Hypertension suboptimally controlled.",
        plan: "Commence insulin glargine. Uptitrate Amlodipine. Endocrine review. Diabetes educator consult. Renal dietitian referral.",
      },
    },
    {
      id: "enc-ra-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Endocrinology",
      clinician: "Dr Patricia Lam",
      note: {
        subjective: "BSL improving, 8-12 range. No hypoglycaemic episodes. Tolerating diet well.",
        objective: "BSL 9.2 fasting. BP 148/92. eGFR stable 43.",
        assessment: "T2DM improving on insulin. BP better controlled.",
        plan: "Continue insulin. Increase Perindopril to 8mg. Renal clinic follow-up 4 weeks. Discharge planning tomorrow.",
      },
    },
  ],
};

const isabelleDupont: Patient = {
  id: "isabelle-dupont",
  mrn: "RMH-451823",
  medicareNumber: "4518 23967 3",
  ihi: "8003 4519 0023 7651",
  firstName: "Isabelle",
  lastName: "Dupont",
  dob: "1979-07-08",
  age: 45,
  sex: "Female",
  bloodType: "B+",
  address: "7 Collins St, Melbourne VIC 3000",
  phone: "0407 182 394",
  nextOfKin: { name: "Henri Dupont", relationship: "Husband", phone: "0418 293 018" },
  gp: { name: "Dr Sandra Lee", practice: "City Medical Centre", phone: "(03) 9654 2100" },
  ward: "5B",
  bedNumber: "3",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-23",
  treatingClinician: "Dr Michael Torres",
  department: "Respiratory Medicine",
  fallsRisk: "Low",
  ewsScore: 4,
  alerts: [],
  allergies: [],
  diagnoses: [
    { icdCode: "I26.9", description: "Pulmonary embolism without acute cor pulmonale", shortName: "Pulmonary Embolism", status: "Active" },
    { icdCode: "R00.0", description: "Tachycardia, unspecified", shortName: "Tachycardia", status: "Active" },
  ],
  medications: [
    { id: "m-id-1", name: "Rivaroxaban", brandName: "Xarelto", dose: "15mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: true, prescriber: "Dr Michael Torres", startDate: "2026-04-23" },
    { id: "m-id-2", name: "Enoxaparin", brandName: "Clexane", dose: "90mg", frequency: "BD", route: "SC", status: "Active", isHighAlert: true, prescriber: "Dr Michael Torres", startDate: "2026-04-23" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 110, diastolicBP: 70, heartRate: 115, respiratoryRate: 24, temperature: 37.6, oxygenSaturation: 91, ewsScore: 6, painScore: 8 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 111, diastolicBP: 71, heartRate: 112, respiratoryRate: 23, temperature: 37.5, oxygenSaturation: 92, ewsScore: 5, painScore: 7 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 112, diastolicBP: 72, heartRate: 110, respiratoryRate: 23, temperature: 37.4, oxygenSaturation: 92, ewsScore: 5, painScore: 7 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 112, diastolicBP: 72, heartRate: 108, respiratoryRate: 22, temperature: 37.4, oxygenSaturation: 93, ewsScore: 4, painScore: 6 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 112, diastolicBP: 72, heartRate: 102, respiratoryRate: 22, temperature: 37.4, oxygenSaturation: 93, ewsScore: 4, painScore: 6 },
  ],
  encounters: [
    {
      id: "enc-id-1",
      type: "Admission",
      date: "2026-04-23",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr Michael Torres",
      note: {
        subjective: "45yo female presenting with sudden onset dyspnoea and right pleuritic chest pain. No recent surgery, travel 3 weeks ago to France. Currently on OCP.",
        objective: "HR 108 BP 112/70 RR 22 SpO2 91% RA. CT-PA: bilateral PE, right > left. D-dimer markedly elevated 8.4.",
        assessment: "Bilateral pulmonary embolism. OCP to be ceased. Anticoagulation commenced.",
        plan: "Therapeutic anticoagulation with Rivaroxaban and bridging Enoxaparin. Supplemental oxygen. Thrombophilia screen ordered. Haematology referral. Cease OCP.",
      },
    },
    {
      id: "enc-id-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr Michael Torres",
      note: {
        subjective: "Dyspnoea improving. Pleuritic pain 6/10, tolerable.",
        objective: "HR 102 SpO2 93% on 2L O2. Haemodynamically stable. Anticoagulation therapeutic.",
        assessment: "Bilateral PE — improving on anticoagulation therapy.",
        plan: "Continue Rivaroxaban. Wean oxygen as tolerated. Echo to assess RV function. Thrombophilia results pending. Haematology review arranged.",
      },
    },
  ],
};

const danielKowalczyk: Patient = {
  id: "daniel-kowalczyk",
  mrn: "RMH-380941",
  medicareNumber: "3809 41753 1",
  ihi: "8003 3810 0047 5392",
  firstName: "Daniel",
  lastName: "Kowalczyk",
  dob: "1986-11-30",
  age: 38,
  sex: "Male",
  bloodType: "A-",
  address: "93 Smith St, Collingwood VIC 3066",
  phone: "0421 938 472",
  nextOfKin: { name: "Anna Kowalczyk", relationship: "Wife", phone: "0432 817 293" },
  gp: { name: "Dr Ben Harris", practice: "Collingwood General Practice", phone: "(03) 9417 3810" },
  ward: "5A",
  bedNumber: "8",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-23",
  treatingClinician: "Dr Rachel Kim",
  department: "Neurosurgery",
  fallsRisk: "Medium",
  ewsScore: 2,
  alerts: [],
  allergies: [
    { allergen: "Codeine", type: "Drug", reaction: "Nausea and vomiting", severity: "Moderate", verified: true },
  ],
  diagnoses: [
    { icdCode: "M51.16", description: "Intervertebral disc degeneration, lumbar region", shortName: "L4/L5 Disc Herniation", status: "Active" },
    { icdCode: "G89.18", description: "Other acute postprocedural pain", shortName: "Post-operative pain", status: "Active" },
  ],
  medications: [
    { id: "m-dk-1", name: "Oxycodone", brandName: "Endone", dose: "5mg", frequency: "4-hrly PRN", route: "Oral", status: "Active", isHighAlert: true, prescriber: "Dr Rachel Kim", startDate: "2026-04-23" },
    { id: "m-dk-2", name: "Paracetamol", dose: "1g", frequency: "QID", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Rachel Kim", startDate: "2026-04-23" },
    { id: "m-dk-3", name: "Celecoxib", brandName: "Celebrex", dose: "200mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Rachel Kim", startDate: "2026-04-23" },
    { id: "m-dk-4", name: "Ondansetron", brandName: "Zofran", dose: "4mg", frequency: "TDS PRN", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Rachel Kim", startDate: "2026-04-23" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 126, diastolicBP: 80, heartRate: 72, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 99, ewsScore: 1, painScore: 7 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 125, diastolicBP: 79, heartRate: 70, respiratoryRate: 16, temperature: 36.9, oxygenSaturation: 99, ewsScore: 1, painScore: 7 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 124, diastolicBP: 78, heartRate: 69, respiratoryRate: 16, temperature: 36.9, oxygenSaturation: 99, ewsScore: 2, painScore: 6 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 124, diastolicBP: 78, heartRate: 68, respiratoryRate: 16, temperature: 36.9, oxygenSaturation: 99, ewsScore: 2, painScore: 5 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 124, diastolicBP: 78, heartRate: 68, respiratoryRate: 16, temperature: 36.9, oxygenSaturation: 99, ewsScore: 2, painScore: 5 },
  ],
  encounters: [
    {
      id: "enc-dk-1",
      type: "Procedure",
      date: "2026-04-23",
      facility: "Royal Melbourne Hospital",
      department: "Neurosurgery",
      clinician: "Dr Rachel Kim",
      note: {
        subjective: "38yo male for elective L4/L5 microdiscectomy. Longstanding sciatica left leg unresponsive to conservative management. Codeine allergy documented.",
        objective: "Pre-op obs stable. Procedure performed under GA without complications. EBL minimal. Intraoperative findings consistent with L4/L5 disc herniation compressing left nerve root.",
        assessment: "Uncomplicated L4/L5 microdiscectomy. Good decompression achieved.",
        plan: "Post-op analgesia protocol avoiding codeine — Oxycodone and Paracetamol. Physio day 1. Ambulate with assistance. Ondansetron PRN.",
      },
    },
    {
      id: "enc-dk-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Neurosurgery",
      clinician: "Dr Rachel Kim",
      note: {
        subjective: "Pain 5/10 improving. Left leg sciatica significantly reduced. Walking short distances with frame.",
        objective: "Wound clean and dry. Neuro exam: left leg power improving 4/5 → 4+/5. Reflexes intact.",
        assessment: "Good early post-operative recovery. Neurological improvement evident.",
        plan: "Upgrade to oral analgesia. Increase mobilisation. Discharge planning day 2. Outpatient physio referral.",
      },
    },
  ],
};

const evelynNakamura: Patient = {
  id: "evelyn-nakamura",
  mrn: "RMH-820374",
  medicareNumber: "8203 74182 4",
  ihi: "8003 8204 0018 2437",
  firstName: "Evelyn",
  lastName: "Nakamura",
  dob: "1943-02-19",
  age: 82,
  sex: "Female",
  bloodType: "AB+",
  address: "12 Lygon St, Carlton VIC 3053",
  phone: "0398 472 819",
  nextOfKin: { name: "Kenji Nakamura", relationship: "Son", phone: "0412 938 472" },
  gp: { name: "Dr Yuki Tanaka", practice: "Carlton Medical Group", phone: "(03) 9347 1820" },
  ward: "4A",
  bedNumber: "2",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-21",
  treatingClinician: "Dr William Patel",
  department: "Respiratory Medicine",
  fallsRisk: "High",
  ewsScore: 5,
  alerts: ["FALLS RISK — HIGH", "HEARING IMPAIRMENT"],
  allergies: [
    { allergen: "Sulfonamides", type: "Drug", reaction: "Urticarial rash", severity: "Moderate", verified: true },
  ],
  diagnoses: [
    { icdCode: "J18.9", description: "Pneumonia, unspecified organism", shortName: "Community-acquired Pneumonia", status: "Active" },
    { icdCode: "I48.91", description: "Unspecified atrial fibrillation", shortName: "Atrial Fibrillation", status: "Chronic" },
    { icdCode: "M81.0", description: "Age-related osteoporosis without current pathological fracture", shortName: "Osteoporosis", status: "Chronic" },
  ],
  medications: [
    { id: "m-en-1", name: "Amoxicillin-Clavulanate", brandName: "Augmentin", dose: "875/125mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-21" },
    { id: "m-en-2", name: "Azithromycin", dose: "500mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-21" },
    { id: "m-en-3", name: "Warfarin", dose: "3mg", frequency: "Nocte", route: "Oral", status: "Active", isHighAlert: true, prescriber: "Dr William Patel", startDate: "2024-03-15" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 138, diastolicBP: 82, heartRate: 96, respiratoryRate: 26, temperature: 39.1, oxygenSaturation: 89, ewsScore: 7, painScore: 4 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 136, diastolicBP: 80, heartRate: 95, respiratoryRate: 25, temperature: 38.9, oxygenSaturation: 90, ewsScore: 6, painScore: 3 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 134, diastolicBP: 80, heartRate: 94, respiratoryRate: 25, temperature: 38.7, oxygenSaturation: 91, ewsScore: 6, painScore: 3 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 133, diastolicBP: 79, heartRate: 94, respiratoryRate: 24, temperature: 38.6, oxygenSaturation: 92, ewsScore: 5, painScore: 3 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 132, diastolicBP: 78, heartRate: 94, respiratoryRate: 24, temperature: 38.6, oxygenSaturation: 92, ewsScore: 5, painScore: 3 },
  ],
  encounters: [
    {
      id: "enc-en-1",
      type: "Admission",
      date: "2026-04-21",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr William Patel",
      note: {
        subjective: "82yo female with known AF and osteoporosis presenting with 3-day history of productive cough, fever, and increasing dyspnoea. Lives alone. Son concerned about functional decline. Hearing impairment noted — communicate clearly. Sulfonamide allergy documented.",
        objective: "Temp 39.1°C HR 96 BP 138/82 RR 26 SpO2 89% RA. CXR: right lower lobe consolidation. WBC 18.2. CRP 214. Sputum culture pending. INR 2.4 (therapeutic on Warfarin).",
        assessment: "Community-acquired pneumonia. Atrial fibrillation — rate controlled. Sulfonamide allergy documented — dual therapy with Augmentin and Azithromycin commenced.",
        plan: "Commence dual antibiotic therapy. Supplemental O2 to maintain SpO2 >92%. Falls risk precautions — high risk. Continue Warfarin with INR monitoring. Aged care OT review. Physiotherapy for airway clearance.",
      },
    },
    {
      id: "enc-en-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr William Patel",
      note: {
        subjective: "Fever persisting but trending down. Cough productive, less frequent. Son present and reports patient more alert than yesterday.",
        objective: "Temp 38.6°C HR 94 SpO2 92% on 2L O2. CXR unchanged. WBC improving 14.6. CRP 168. INR 2.6.",
        assessment: "CAP — slowly responding to antibiotics. AF rate-controlled. Falls risk ongoing.",
        plan: "Continue antibiotics for full course. Maintain O2 support. Falls precautions reinforced. INR recheck 48 hours. Social work referral for discharge planning. Occupational therapy home assessment arranged.",
      },
    },
  ],
};

const thomasSullivan: Patient = {
  id: "thomas-sullivan",
  mrn: "RMH-552819",
  medicareNumber: "5528 19046 2",
  ihi: "8003 5529 0010 4628",
  firstName: "Thomas",
  lastName: "Sullivan",
  dob: "1970-08-14",
  age: 55,
  sex: "Male",
  bloodType: "O-",
  address: "55 Punt Rd, Richmond VIC 3121",
  phone: "0409 281 937",
  nextOfKin: { name: "Claire Sullivan", relationship: "Wife", phone: "0421 837 192" },
  gp: { name: "Dr Peter Walsh", practice: "Richmond Health", phone: "(03) 9428 1930" },
  ward: "ED",
  bedNumber: "ED-4",
  admissionStatus: "ED",
  admissionDate: "2026-04-24",
  treatingClinician: "Dr Emma Walsh",
  department: "Emergency Medicine",
  fallsRisk: "Low",
  ewsScore: 6,
  alerts: ["CONTRAST ALLERGY — IODINE", "RESUS BAY"],
  allergies: [
    { allergen: "Iodine contrast", type: "Contrast", reaction: "Anaphylaxis", severity: "Life-threatening", verified: true },
  ],
  diagnoses: [
    { icdCode: "R07.9", description: "Chest pain, unspecified", shortName: "Chest Pain", status: "Active" },
    { icdCode: "I10", description: "Essential hypertension", shortName: "Hypertension", status: "Chronic" },
    { icdCode: "I25.10", description: "Atherosclerotic heart disease of native coronary artery", shortName: "Query ACS", status: "Suspected" },
  ],
  medications: [
    { id: "m-ts-1", name: "Aspirin", dose: "300mg", frequency: "Stat", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Emma Walsh", startDate: "2026-04-24" },
    { id: "m-ts-2", name: "GTN spray", dose: "400mcg", frequency: "PRN", route: "SL", status: "Active", isHighAlert: false, prescriber: "Dr Emma Walsh", startDate: "2026-04-24" },
    { id: "m-ts-3", name: "Heparin", dose: "5000 units bolus", frequency: "Stat then infusion", route: "IV", status: "Active", isHighAlert: true, prescriber: "Dr Emma Walsh", startDate: "2026-04-24" },
    { id: "m-ts-4", name: "Morphine", dose: "2.5mg", frequency: "PRN 30min", route: "IV", status: "Active", isHighAlert: true, prescriber: "Dr Emma Walsh", startDate: "2026-04-24" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 168, diastolicBP: 100, heartRate: 114, respiratoryRate: 20, temperature: 37.2, oxygenSaturation: 94, ewsScore: 7, painScore: 9 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 165, diastolicBP: 98, heartRate: 110, respiratoryRate: 20, temperature: 37.2, oxygenSaturation: 95, ewsScore: 6, painScore: 8 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 164, diastolicBP: 98, heartRate: 109, respiratoryRate: 20, temperature: 37.2, oxygenSaturation: 95, ewsScore: 6, painScore: 8 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 163, diastolicBP: 97, heartRate: 109, respiratoryRate: 20, temperature: 37.2, oxygenSaturation: 95, ewsScore: 6, painScore: 8 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 162, diastolicBP: 96, heartRate: 108, respiratoryRate: 20, temperature: 37.2, oxygenSaturation: 95, ewsScore: 6, painScore: 8 },
  ],
  encounters: [
    {
      id: "enc-ts-1",
      type: "ED Triage",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Emergency Medicine",
      clinician: "Dr Emma Walsh",
      note: {
        subjective: "55yo male presenting via ambulance with acute onset central chest pain radiating to left arm, onset approximately 45 minutes prior to arrival. Associated diaphoresis and nausea. Background hypertension. Iodine contrast allergy documented — anaphylaxis.",
        objective: "HR 114 BP 168/100 RR 20 SpO2 94% RA. ECG: ST depression lateral leads V5-V6, I, aVL. Troponin I pending. CXR unremarkable. Iodine contrast allergy noted — CT coronary angiography will require alternative imaging strategy.",
        assessment: "Likely non-ST elevation ACS. Iodine contrast allergy (anaphylaxis) documented — cardiology notified. Resus bay monitoring commenced.",
        plan: "Aspirin 300mg stat. IV Heparin commenced. GTN SL PRN chest pain. IV Morphine PRN. Serial ECGs and troponin. Cardiology consult requested. Iodine allergy flagged for any imaging. Monitor in resus bay.",
      },
    },
  ],
};

const priyaKrishnamurthy: Patient = {
  id: "priya-krishnamurthy",
  mrn: "RMH-293847",
  medicareNumber: "2938 47201 1",
  ihi: "8003 2939 0072 0193",
  firstName: "Priya",
  lastName: "Krishnamurthy",
  dob: "1995-04-03",
  age: 29,
  sex: "Female",
  bloodType: "B+",
  address: "28 High St, Northcote VIC 3070",
  phone: "0414 293 817",
  nextOfKin: { name: "Raj Krishnamurthy", relationship: "Father", phone: "0418 392 847" },
  gp: { name: "Dr Amy Chen", practice: "Northcote Family Medicine", phone: "(03) 9489 2930" },
  ward: "5A",
  bedNumber: "11",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-23",
  treatingClinician: "Dr Simon Burke",
  department: "General Surgery",
  fallsRisk: "Low",
  ewsScore: 1,
  alerts: [],
  allergies: [],
  diagnoses: [
    { icdCode: "K37", description: "Unspecified appendicitis", shortName: "Appendicitis", status: "Active" },
    { icdCode: "Z48.89", description: "Encounter for other specified surgical aftercare", shortName: "Post-laparoscopic appendicectomy", status: "Active" },
  ],
  medications: [
    { id: "m-pk-1", name: "Paracetamol", dose: "1g", frequency: "QID", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Simon Burke", startDate: "2026-04-23" },
    { id: "m-pk-2", name: "Ibuprofen", dose: "400mg", frequency: "TDS", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Simon Burke", startDate: "2026-04-23" },
    { id: "m-pk-3", name: "Cefazolin", dose: "1g", frequency: "TDS", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr Simon Burke", startDate: "2026-04-23" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 118, diastolicBP: 74, heartRate: 88, respiratoryRate: 16, temperature: 37.8, oxygenSaturation: 99, ewsScore: 2, painScore: 7 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 117, diastolicBP: 73, heartRate: 82, respiratoryRate: 15, temperature: 37.5, oxygenSaturation: 99, ewsScore: 1, painScore: 5 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 116, diastolicBP: 72, heartRate: 80, respiratoryRate: 14, temperature: 37.2, oxygenSaturation: 99, ewsScore: 1, painScore: 4 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 116, diastolicBP: 72, heartRate: 78, respiratoryRate: 14, temperature: 37.1, oxygenSaturation: 99, ewsScore: 1, painScore: 3 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 116, diastolicBP: 72, heartRate: 76, respiratoryRate: 14, temperature: 37.0, oxygenSaturation: 99, ewsScore: 1, painScore: 3 },
  ],
  encounters: [
    {
      id: "enc-pk-1",
      type: "Procedure",
      date: "2026-04-23",
      facility: "Royal Melbourne Hospital",
      department: "General Surgery",
      clinician: "Dr Simon Burke",
      note: {
        subjective: "29yo female presenting with 24-hour history of periumbilical pain migrating to right iliac fossa, associated nausea and low-grade fever. NKDA. LMP 3 weeks ago. Urine hCG negative.",
        objective: "Temp 37.8°C HR 88 BP 118/74. RIF tenderness with guarding. WBC 14.8. CRP 98. USS equivocal. CT abdomen: inflamed appendix, no perforation. Laparoscopic appendicectomy performed under GA without complications.",
        assessment: "Uncomplicated acute appendicitis. Laparoscopic appendicectomy performed.",
        plan: "Post-operative analgesia with Paracetamol and Ibuprofen. IV Cefazolin prophylaxis. Regular diet when tolerated. Mobilise day 1. Discharge planning day 2.",
      },
    },
    {
      id: "enc-pk-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "General Surgery",
      clinician: "Dr Simon Burke",
      note: {
        subjective: "Pain well controlled 3/10 with oral analgesia. Tolerating light diet. No nausea. Passed flatus. Ambulating independently.",
        objective: "Temp 37.0°C HR 76 BP 116/72. Laparoscopic port sites clean and dry. Abdomen soft. Bowel sounds present.",
        assessment: "Uncomplicated post-operative day 1 following laparoscopic appendicectomy. Recovery progressing well.",
        plan: "Continue oral analgesia. Upgrade to full diet. Cease IV Cefazolin, transition to oral Cefalexin. Discharge tomorrow. Wound review GP in 1 week. Return precautions documented.",
      },
    },
  ],
};

const williamGrant: Patient = {
  id: "william-grant",
  mrn: "RMH-748201",
  medicareNumber: "7482 01394 3",
  ihi: "8003 7483 0013 9428",
  firstName: "William",
  lastName: "Grant",
  dob: "1956-12-07",
  age: 68,
  sex: "Male",
  bloodType: "A+",
  address: "4 Barkly St, St Kilda VIC 3182",
  phone: "0396 284 719",
  nextOfKin: { name: "Dorothy Grant", relationship: "Wife", phone: "0423 748 192" },
  gp: { name: "Dr James O'Brien", practice: "St Kilda Road Medical", phone: "(03) 9537 2840" },
  ward: "5B",
  bedNumber: "6",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-22",
  treatingClinician: "Dr William Patel",
  department: "Respiratory Medicine",
  fallsRisk: "Low",
  ewsScore: 4,
  alerts: [],
  allergies: [
    { allergen: "Penicillin", type: "Drug", reaction: "Urticarial rash", severity: "Moderate", verified: true },
  ],
  diagnoses: [
    { icdCode: "J44.1", description: "COPD with acute exacerbation", shortName: "COPD Exacerbation", status: "Active" },
    { icdCode: "J96.01", description: "Acute respiratory failure with hypoxia", shortName: "Type 1 Respiratory Failure", status: "Active" },
  ],
  medications: [
    { id: "m-wg-1", name: "Salbutamol nebuliser", dose: "2.5mg", frequency: "4-hrly", route: "Inhaled", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-22" },
    { id: "m-wg-2", name: "Ipratropium nebuliser", dose: "500mcg", frequency: "6-hrly", route: "Inhaled", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-22" },
    { id: "m-wg-3", name: "Prednisolone", dose: "50mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-22" },
    { id: "m-wg-4", name: "Doxycycline", dose: "100mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr William Patel", startDate: "2026-04-22" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 138, diastolicBP: 86, heartRate: 96, respiratoryRate: 28, temperature: 37.9, oxygenSaturation: 84, ewsScore: 7, painScore: 3 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 137, diastolicBP: 85, heartRate: 94, respiratoryRate: 27, temperature: 37.8, oxygenSaturation: 86, ewsScore: 6, painScore: 2 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 136, diastolicBP: 84, heartRate: 93, respiratoryRate: 27, temperature: 37.8, oxygenSaturation: 87, ewsScore: 5, painScore: 2 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 136, diastolicBP: 84, heartRate: 92, respiratoryRate: 26, temperature: 37.8, oxygenSaturation: 88, ewsScore: 5, painScore: 2 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 136, diastolicBP: 84, heartRate: 92, respiratoryRate: 26, temperature: 37.8, oxygenSaturation: 89, ewsScore: 4, painScore: 2 },
  ],
  encounters: [
    {
      id: "enc-wg-1",
      type: "Admission",
      date: "2026-04-22",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr William Patel",
      note: {
        subjective: "68yo male with known COPD presenting with 3-day worsening dyspnoea, increased sputum production (purulent), and reduced exercise tolerance. 40 pack-year smoking history, quit 5 years ago. Penicillin allergy — rash.",
        objective: "HR 96 BP 138/86 RR 28 Temp 37.9°C SpO2 84% RA. ABG: pH 7.36 pO2 52 pCO2 52 HCO3 29. CXR: hyperinflation, no consolidation. FEV1 historically 38% predicted.",
        assessment: "Acute exacerbation of COPD with type 1 respiratory failure. Penicillin allergy documented — Doxycycline commenced as alternative antibiotic.",
        plan: "Salbutamol and Ipratropium nebulisers. Prednisolone 50mg Mane. Doxycycline for infective exacerbation. Controlled O2 therapy to maintain SpO2 88-92%. Respiratory physiotherapy. Smoking cessation support. Consider NIV if deteriorating.",
      },
    },
    {
      id: "enc-wg-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Respiratory Medicine",
      clinician: "Dr William Patel",
      note: {
        subjective: "Dyspnoea improving. Sputum less purulent. Feels more comfortable. Wife reports he slept better last night.",
        objective: "HR 92 RR 26 SpO2 89% on 2L controlled O2. Chest auscultation: scattered wheeze, improving. ABG: pH 7.38 pO2 58 pCO2 50.",
        assessment: "COPD exacerbation — slowly responding to treatment. Type 1 respiratory failure improving.",
        plan: "Continue nebulisers and Prednisolone. Wean oxygen gradually. Respiratory physio twice daily. Pulmonary rehab referral. Inhaler technique education. Anticipate discharge day 5-6.",
      },
    },
  ],
};

const sandraOkonkwo: Patient = {
  id: "sandra-okonkwo",
  mrn: "RMH-193847",
  medicareNumber: "1938 47502 2",
  ihi: "8003 1939 0045 0293",
  firstName: "Sandra",
  lastName: "Okonkwo",
  dob: "1972-05-25",
  age: 51,
  sex: "Female",
  bloodType: "O+",
  address: "71 Nicholson St, Brunswick VIC 3056",
  phone: "0408 193 847",
  nextOfKin: { name: "Emmanuel Okonkwo", relationship: "Husband", phone: "0419 384 729" },
  gp: { name: "Dr David Kim", practice: "Brunswick Medical Centre", phone: "(03) 9387 2910" },
  ward: "ICU",
  bedNumber: "ICU-3",
  admissionStatus: "ICU",
  admissionDate: "2026-04-20",
  treatingClinician: "Dr James Chen",
  department: "Intensive Care",
  fallsRisk: "High",
  ewsScore: 9,
  alerts: ["CONTACT PRECAUTIONS — MRSA", "ICU ISOLATION REQUIRED", "VANCOMYCIN ALLERGY"],
  allergies: [
    { allergen: "Vancomycin", type: "Drug", reaction: "Red Man Syndrome — anaphylactoid reaction", severity: "Severe", verified: true },
  ],
  diagnoses: [
    { icdCode: "A41.9", description: "Sepsis, unspecified organism", shortName: "Sepsis", status: "Active" },
    { icdCode: "B95.62", description: "Methicillin-resistant Staphylococcus aureus infection", shortName: "MRSA Bacteraemia", status: "Active" },
    { icdCode: "N17.9", description: "Acute kidney injury, unspecified", shortName: "Acute Kidney Injury", status: "Active" },
  ],
  medications: [
    { id: "m-so-1", name: "Linezolid", brandName: "Zyvox", dose: "600mg", frequency: "BD", route: "IV", status: "Active", isHighAlert: true, prescriber: "Dr James Chen", startDate: "2026-04-20" },
    { id: "m-so-2", name: "Noradrenaline", dose: "0.1–0.3 mcg/kg/min", frequency: "Continuous", route: "IV", status: "Active", isHighAlert: true, prescriber: "Dr James Chen", startDate: "2026-04-20" },
    { id: "m-so-3", name: "Piperacillin-Tazobactam", brandName: "Tazocin", dose: "4.5g", frequency: "6-hrly", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr James Chen", startDate: "2026-04-20" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 82, diastolicBP: 48, heartRate: 132, respiratoryRate: 30, temperature: 39.4, oxygenSaturation: 88, ewsScore: 10, painScore: 8 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 84, diastolicBP: 50, heartRate: 128, respiratoryRate: 29, temperature: 39.3, oxygenSaturation: 89, ewsScore: 9, painScore: 8 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 86, diastolicBP: 51, heartRate: 126, respiratoryRate: 29, temperature: 39.2, oxygenSaturation: 89, ewsScore: 9, painScore: 7 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 87, diastolicBP: 52, heartRate: 125, respiratoryRate: 28, temperature: 39.2, oxygenSaturation: 90, ewsScore: 9, painScore: 7 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 88, diastolicBP: 52, heartRate: 124, respiratoryRate: 28, temperature: 39.1, oxygenSaturation: 90, ewsScore: 9, painScore: 7 },
  ],
  encounters: [
    {
      id: "enc-so-1",
      type: "Admission",
      date: "2026-04-20",
      facility: "Royal Melbourne Hospital",
      department: "Intensive Care",
      clinician: "Dr James Chen",
      note: {
        subjective: "51yo female transferred from ED with septic shock. Source suspected line-related MRSA bacteraemia — blood cultures drawn. Vancomycin allergy documented (Red Man Syndrome) — Linezolid commenced as alternative. Contact precautions and ICU isolation in place.",
        objective: "Temp 39.4°C HR 132 BP 82/48 RR 30 SpO2 88% on high-flow O2. WBC 28.4 CRP 348. Lactate 4.2. Blood cultures positive MRSA. Creatinine 284 (baseline ~80) — AKI. Vasopressor support commenced.",
        assessment: "Septic shock secondary to MRSA bacteraemia. AKI stage 3. Vancomycin allergy — Linezolid used as MRSA-active alternative. Broad cover with Piperacillin-Tazobactam.",
        plan: "ICU isolation. Contact precautions strictly observed. Linezolid IV BD for MRSA. Piperacillin-Tazobactam for gram-negative cover. Noradrenaline infusion for vasopressor support. Fluid resuscitation. Strict fluid balance. Renal team review — risk of dialysis. Infectious diseases consult.",
      },
    },
    {
      id: "enc-so-2",
      type: "Nursing",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Intensive Care",
      clinician: "Dr James Chen",
      note: {
        subjective: "Patient sedated and intubated. Husband at bedside. Contact precautions maintained. No new symptoms elicitable.",
        objective: "HR 124 BP 88/52 on Noradrenaline 0.2 mcg/kg/min. Temp 39.1°C SpO2 90% on ventilator FiO2 0.55. Urine output 18mL/hr — oliguric. Creatinine 312. Blood cultures — MRSA confirmed. Linezolid levels pending.",
        assessment: "MRSA bacteraemia with septic shock and AKI. Persistently critical. Isolation and contact precautions maintained.",
        plan: "Continue Linezolid and Tazocin. Titrate Noradrenaline to MAP >65. Renal team to review for CVVHD. Family meeting today. Infection control review. Daily blood cultures.",
      },
    },
  ],
};

const jamesMoretti: Patient = {
  id: "james-moretti",
  mrn: "RMH-674920",
  medicareNumber: "6749 20183 4",
  ihi: "8003 6750 0018 3492",
  firstName: "James",
  lastName: "Moretti",
  dob: "1947-01-11",
  age: 77,
  sex: "Male",
  bloodType: "B-",
  address: "33 Chapel St, Prahran VIC 3181",
  phone: "0396 182 749",
  nextOfKin: { name: "Rosa Moretti", relationship: "Wife", phone: "0412 674 829" },
  gp: { name: "Dr Patricia Wong", practice: "Prahran Medical Centre", phone: "(03) 9529 1830" },
  ward: "5A",
  bedNumber: "5",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-22",
  treatingClinician: "Dr Rachel Kim",
  department: "Orthopaedics",
  fallsRisk: "High",
  ewsScore: 2,
  alerts: ["FALLS RISK — HIGH", "POST-THR PRECAUTIONS"],
  allergies: [],
  diagnoses: [
    { icdCode: "M16.11", description: "Unilateral primary osteoarthritis, right hip", shortName: "Right Hip OA", status: "Chronic" },
    { icdCode: "Z96.641", description: "Presence of right artificial hip joint", shortName: "Right THR Day 2", status: "Active" },
    { icdCode: "D62", description: "Acute posthaemorrhagic anaemia", shortName: "Post-op Anaemia", status: "Active" },
  ],
  medications: [
    { id: "m-jm-1", name: "Oxycodone", brandName: "Endone", dose: "5mg", frequency: "4-hrly PRN", route: "Oral", status: "Active", isHighAlert: true, prescriber: "Dr Rachel Kim", startDate: "2026-04-22" },
    { id: "m-jm-2", name: "Paracetamol", dose: "1g", frequency: "QID", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Rachel Kim", startDate: "2026-04-22" },
    { id: "m-jm-3", name: "Enoxaparin", brandName: "Clexane", dose: "40mg", frequency: "Mane", route: "SC", status: "Active", isHighAlert: true, prescriber: "Dr Rachel Kim", startDate: "2026-04-22" },
    { id: "m-jm-4", name: "Ferrous Sulphate", dose: "325mg", frequency: "BD", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Rachel Kim", startDate: "2026-04-23" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 130, diastolicBP: 78, heartRate: 86, respiratoryRate: 17, temperature: 37.4, oxygenSaturation: 96, ewsScore: 2, painScore: 6 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 129, diastolicBP: 77, heartRate: 84, respiratoryRate: 17, temperature: 37.4, oxygenSaturation: 97, ewsScore: 2, painScore: 5 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 128, diastolicBP: 76, heartRate: 83, respiratoryRate: 16, temperature: 37.3, oxygenSaturation: 97, ewsScore: 2, painScore: 5 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 128, diastolicBP: 76, heartRate: 82, respiratoryRate: 16, temperature: 37.3, oxygenSaturation: 97, ewsScore: 2, painScore: 4 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 128, diastolicBP: 76, heartRate: 82, respiratoryRate: 16, temperature: 37.3, oxygenSaturation: 97, ewsScore: 2, painScore: 4 },
  ],
  encounters: [
    {
      id: "enc-jm-1",
      type: "Procedure",
      date: "2026-04-22",
      facility: "Royal Melbourne Hospital",
      department: "Orthopaedics",
      clinician: "Dr Rachel Kim",
      note: {
        subjective: "77yo male with longstanding right hip osteoarthritis presenting for elective right total hip replacement. Pain significantly limiting mobility and quality of life. NKDA. Medically optimised pre-operatively.",
        objective: "Pre-op Hb 138. Right THR performed under spinal anaesthesia without intraoperative complications. Cementless prosthesis inserted. EBL 450mL. Post-op Hb 94 — iron supplementation commenced.",
        assessment: "Right total hip replacement completed. Post-operative anaemia. Falls risk — high due to age and post-THR precautions.",
        plan: "Post-THR precautions: avoid hip flexion >90°, internal rotation, adduction across midline. Enoxaparin 40mg SC Mane for VTE prophylaxis. Oxycodone and Paracetamol for analgesia. Ferrous Sulphate for anaemia. Physio from day 1. Falls prevention — call bell in reach, non-slip footwear, bed rails.",
      },
    },
    {
      id: "enc-jm-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Orthopaedics",
      clinician: "Dr Rachel Kim",
      note: {
        subjective: "Day 2 post right THR. Pain 4/10 with oral analgesia. Mobilised with walking frame this morning with physiotherapy — tolerated well. Wife present.",
        objective: "HR 82 BP 128/76 SpO2 97%. Wound: dressing intact, no signs of infection. Hb 98 — stable. Right hip: no dislocation signs, good range of movement within precautions.",
        assessment: "Good progress day 2 post right THR. Post-operative anaemia improving. VTE prophylaxis in place.",
        plan: "Continue Enoxaparin. Maintain THR precautions. Increase mobilisation — aim walking 20m with frame. OT assessment for home equipment. Discharge planning day 4-5. Outpatient orthopaedic review 6 weeks.",
      },
    },
  ],
};

const aishaAlHassan: Patient = {
  id: "aisha-al-hassan",
  mrn: "RMH-502847",
  medicareNumber: "5028 47193 1",
  ihi: "8003 5029 0041 9372",
  firstName: "Aisha",
  lastName: "Al-Hassan",
  dob: "1991-08-29",
  age: 34,
  sex: "Female",
  bloodType: "A+",
  address: "19 Royal Parade, Parkville VIC 3052",
  phone: "0403 518 294",
  nextOfKin: { name: "Tariq Al-Hassan", relationship: "Husband", phone: "0421 503 847" },
  gp: { name: "Dr Nadia Malik", practice: "Parkville Women's Health", phone: "(03) 9347 2810" },
  ward: "4A",
  bedNumber: "9",
  admissionStatus: "Inpatient",
  admissionDate: "2026-04-22",
  treatingClinician: "Dr Fatima Malik",
  department: "Obstetrics",
  fallsRisk: "Low",
  ewsScore: 2,
  alerts: ["PREGNANCY — 16 WEEKS"],
  allergies: [],
  diagnoses: [
    { icdCode: "O21.1", description: "Hyperemesis gravidarum with metabolic disturbance", shortName: "Hyperemesis Gravidarum", status: "Active" },
    { icdCode: "Z34.16", description: "Encounter for supervision of normal first pregnancy, second trimester", shortName: "Pregnancy 16 Weeks", status: "Active" },
  ],
  medications: [
    { id: "m-ah-1", name: "Ondansetron", brandName: "Zofran", dose: "8mg", frequency: "TDS", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr Fatima Malik", startDate: "2026-04-22" },
    { id: "m-ah-2", name: "Metoclopramide", brandName: "Maxolon", dose: "10mg", frequency: "TDS", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr Fatima Malik", startDate: "2026-04-22" },
    { id: "m-ah-3", name: "Hartmann's Solution", dose: "1000mL", frequency: "8-hrly", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr Fatima Malik", startDate: "2026-04-22" },
    { id: "m-ah-4", name: "Thiamine", dose: "100mg", frequency: "Mane", route: "IV", status: "Active", isHighAlert: false, prescriber: "Dr Fatima Malik", startDate: "2026-04-22" },
    { id: "m-ah-5", name: "Folate", dose: "5mg", frequency: "Mane", route: "Oral", status: "Active", isHighAlert: false, prescriber: "Dr Fatima Malik", startDate: "2026-04-22" },
  ],
  vitals: [
    { timestamp: "2026-04-22T08:00:00", systolicBP: 104, diastolicBP: 66, heartRate: 102, respiratoryRate: 18, temperature: 36.9, oxygenSaturation: 99, ewsScore: 3, painScore: 4 },
    { timestamp: "2026-04-22T20:00:00", systolicBP: 103, diastolicBP: 65, heartRate: 100, respiratoryRate: 17, temperature: 36.8, oxygenSaturation: 99, ewsScore: 2, painScore: 4 },
    { timestamp: "2026-04-23T08:00:00", systolicBP: 103, diastolicBP: 64, heartRate: 98, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 99, ewsScore: 2, painScore: 3 },
    { timestamp: "2026-04-23T20:00:00", systolicBP: 102, diastolicBP: 64, heartRate: 97, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 99, ewsScore: 2, painScore: 3 },
    { timestamp: "2026-04-24T08:00:00", systolicBP: 102, diastolicBP: 64, heartRate: 96, respiratoryRate: 16, temperature: 36.8, oxygenSaturation: 99, ewsScore: 2, painScore: 3 },
  ],
  encounters: [
    {
      id: "enc-ah-1",
      type: "Admission",
      date: "2026-04-22",
      facility: "Royal Melbourne Hospital",
      department: "Obstetrics",
      clinician: "Dr Fatima Malik",
      note: {
        subjective: "34yo G1P0 at 16 weeks gestation presenting with intractable nausea and vomiting for 3 weeks, unable to tolerate oral intake. Weight loss 4kg since 12-week scan. Husband reports she has been unable to keep any food or fluids down. NKDA.",
        objective: "HR 102 BP 104/66 SpO2 99%. Weight 54kg. Clinically dehydrated. UEC: Na 133 K 3.1 Cl 94 — hypochloraemic hypokalaemia. Urine ketones +++. USS foetal wellbeing: normal foetal movements, heart rate 156bpm, appropriate for dates.",
        assessment: "Hyperemesis gravidarum with metabolic disturbance — hypochloraemic hypokalaemia. Foetal wellbeing confirmed on USS. Dehydration secondary to vomiting.",
        plan: "IV Hartmann's solution for rehydration. IV Thiamine to prevent Wernicke encephalopathy. IV Ondansetron and Metoclopramide for antiemesis. Folate supplementation. Strict fluid balance. Daily UEC. Dietitian referral. Advance diet as tolerated — start with clear fluids and small sips.",
      },
    },
    {
      id: "enc-ah-2",
      type: "Ward Round",
      date: "2026-04-24",
      facility: "Royal Melbourne Hospital",
      department: "Obstetrics",
      clinician: "Dr Fatima Malik",
      note: {
        subjective: "Nausea improving with IV antiemetics. Tolerating small sips of water and clear fluids. Vomiting reduced to 2 episodes in last 24 hours. Feeling more rested. Husband very supportive.",
        objective: "HR 96 BP 102/64. Urine ketones +. UEC: Na 137 K 3.6 — improving. Weight 54.2kg. Foetal heart tones confirmed with Doppler 158bpm.",
        assessment: "Hyperemesis gravidarum — improving with IV rehydration and antiemetics. Electrolytes correcting. Foetal wellbeing maintained.",
        plan: "Continue IV antiemetics. Transition to oral when tolerating adequate fluids. Advance diet slowly — clear fluids to light diet. Continue IV Hartmann's. Recheck UEC tomorrow. Discuss discharge when oral intake established. Community midwife follow-up arranged.",
      },
    },
  ],
};

export const supportingPatients: Patient[] = [
  margaretThompson,
  robertAdeyemi,
  isabelleDupont,
  danielKowalczyk,
  evelynNakamura,
  thomasSullivan,
  priyaKrishnamurthy,
  williamGrant,
  sandraOkonkwo,
  jamesMoretti,
  aishaAlHassan,
];
